# This file was generated by GoReleaser. DO NOT EDIT.
class Lab < Formula
  desc "A cli tool with gitlab."
  homepage "https://github.com/Ackerr/lab"
  version "0.2.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ackerr/lab/releases/download/v0.2.12/lab_Darwin_x86_64.tar.gz"
    sha256 "0c75bce325a44b42d618652e8f27f2af519574b8e97f369ca848c13dfd068a54"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Ackerr/lab/releases/download/v0.2.12/lab_Linux_x86_64.tar.gz"
    sha256 "82c469ae23fdee561b76533acee5796dccdd01b61784de59a5557eeda13b9106"
  end

  def install
    bin.install "lab"
  end

  test do
    system "#{bin}/lab -v"
  end
end
